networks:
  inception:
    name: inception

volumes:
  mariadb:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jlomic/data/mariadb
  wordpress:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/jlomic/data/wordpress

services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    volumes:
     - mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MARIADB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - inception
    ports:
      - 3307:3306
    expose:
      - "3306"
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    volumes:
     - wordpress:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    ports:
      - 9000:9000
    expose:
      - "9000"
    env_file:
      - .env
    restart: always
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    ports:
      - 443:443
    env_file:
      - .env
    restart: on-failure
